### ISSUE TITLE
FORTAGS generating ERROR

### ISSUE THREAD

**Issue by OrionRandD** [raullaasner/fortran-tags#10]
I cannot generate the FORTAGS file.
It gives an error in line 527  
:( 
-------------------------------

fortran-tags.py -g FORTAGS
Traceback (most recent call last):
  File "/home/lea/scimax/user/local-repo/fortran-tags/fortran-tags.py", line 527, in <module>
    total_size = (sum(os.stat(f).st_size for f in args.generate) -
  File "/home/lea/scimax/user/local-repo/fortran-tags/fortran-tags.py", line 527, in <genexpr>
    total_size = (sum(os.stat(f).st_size for f in args.generate) -
FileNotFoundError: [Errno 2] No such file or directory: 'FORTAGS'

--------------------------------------------
Same here:

fortran-tags.py -g ~/Documents/programming_courses/fortran/FORTAGS
Traceback (most recent call last):
  File "/home/lea/scimax/user/local-repo/fortran-tags/./fortran-tags.py", line 527, in <module>
    total_size = (sum(os.stat(f).st_size for f in args.generate)
-
  File "/home/lea/scimax/user/local-repo/fortran-tags/./fortran-tags.py", line 527, in <genexpr>
    total_size = (sum(os.stat(f).st_size for f in args.generate)
-
FileNotFoundError: [Errno 2] No such file or directory: '/home/lea/Documents/programming_courses/fortran/FORTAGS'

--------------------------------------------

Also: could you add it to MELPA?

**Comment by raullaasner** [comment]
Your argument to `fortran-tags.py` should actually be the source file name (or several source file). Like this:

     fortran-tags.py -g main.f90

It then produces a file called `FORTAGS` (you can change that with the `-o` flag).

**Comment by OrionRandD** [comment]
> Your argument to `fortran-tags.py` should actually be the source file name (or several source file). Like this:
> 
> ```
>  fortran-tags.py -g main.f90
> ```
> 
> It then produces a file called `FORTAGS` (you can change that with the `-o` flag).

OK. Thx a lot...
Looking forward to seeing it on MELPA
and also, if possible, an ox-fortran to use it inside orgmode babel sources... :)
